on:
  - push
name: Push
jobs:
  publish:
    name: Build and Publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          npm publish
          git push
